FROM node:24-alpine AS build
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app
COPY . /app

RUN corepack enable
RUN apk add --no-cache python3 make g++

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

ARG WEB_DEFAULT_API
ARG WEB_HOST
ENV WEB_DEFAULT_API=$WEB_DEFAULT_API
ENV WEB_HOST=$WEB_HOST

RUN pnpm --dir web build

FROM nginx:1.27-alpine
COPY docker/cobalt-web-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/web/build /usr/share/nginx/html

EXPOSE 80
